// Emotion to valence/arousal mapping for DEAM IEQ calculations
// Based on Russell's Circumplex Model and VLADI emotion matrices

export interface EmotionAxes {
  valence: number // -1 to +1 (negative to positive)
  arousal: number // -1 to +1 (low energy to high energy)
}

// Mapping of VLADI emotions to valence/arousal coordinates
export const EMOTION_TO_AXES: Record<string, EmotionAxes> = {
  // GREEN QUADRANT (Low arousal, positive to neutral valence)
  Soñoliento: { valence: 0.1, arousal: -0.8 },
  Complaciente: { valence: 0.4, arousal: -0.6 },
  Sosegado: { valence: 0.5, arousal: -0.7 },
  Acogido: { valence: 0.6, arousal: -0.5 },
  Sereno: { valence: 0.7, arousal: -0.6 },
  Apacible: { valence: 0.5, arousal: -0.7 },
  Reflexivo: { valence: 0.3, arousal: -0.6 },
  Pacífico: { valence: 0.6, arousal: -0.7 },
  Cómodo: { valence: 0.6, arousal: -0.5 },
  Despreocupado: { valence: 0.5, arousal: -0.6 },
  Relajado: { valence: 0.6, arousal: -0.7 },
  Tranquilo: { valence: 0.6, arousal: -0.6 },
  Repuesto: { valence: 0.5, arousal: -0.5 },
  Afortunado: { valence: 0.7, arousal: -0.4 },
  Equilibrado: { valence: 0.6, arousal: -0.5 },
  Calmado: { valence: 0.6, arousal: -0.6 },
  Seguro: { valence: 0.7, arousal: -0.4 },
  Satisfecho: { valence: 0.7, arousal: -0.5 },
  Agradecido: { valence: 0.8, arousal: -0.4 },
  Conmovido: { valence: 0.7, arousal: -0.3 },
  "A gusto": { valence: 0.7, arousal: -0.5 },
  Desenfadado: { valence: 0.6, arousal: -0.4 },
  Contento: { valence: 0.7, arousal: -0.3 },
  Afectuoso: { valence: 0.8, arousal: -0.3 },
  Realizado: { valence: 0.8, arousal: -0.2 },

  // YELLOW QUADRANT (High arousal, positive valence)
  Agradable: { valence: 0.6, arousal: 0.2 },
  Jubiloso: { valence: 0.8, arousal: 0.5 },
  Esperanzado: { valence: 0.7, arousal: 0.3 },
  Juguetón: { valence: 0.7, arousal: 0.5 },
  Dichoso: { valence: 0.9, arousal: 0.4 },
  Complacido: { valence: 0.7, arousal: 0.3 },
  Centrado: { valence: 0.6, arousal: 0.4 },
  Feliz: { valence: 0.8, arousal: 0.4 },
  Orgulloso: { valence: 0.8, arousal: 0.5 },
  Encantado: { valence: 0.9, arousal: 0.5 },
  Enérgico: { valence: 0.7, arousal: 0.7 },
  Vivaz: { valence: 0.8, arousal: 0.7 },
  Emocionado: { valence: 0.8, arousal: 0.8 },
  Optimista: { valence: 0.7, arousal: 0.6 },
  Entusiasta: { valence: 0.8, arousal: 0.8 },
  Hiperactivo: { valence: 0.5, arousal: 0.9 },
  Alegre: { valence: 0.8, arousal: 0.6 },
  Motivado: { valence: 0.7, arousal: 0.7 },
  Inspirado: { valence: 0.8, arousal: 0.7 },
  Exaltado: { valence: 0.7, arousal: 0.9 },
  Sorprendido: { valence: 0.3, arousal: 0.8 },
  Animado: { valence: 0.7, arousal: 0.6 },
  Festivo: { valence: 0.8, arousal: 0.7 },
  Eufórico: { valence: 0.9, arousal: 0.9 },
  Extasiado: { valence: 1.0, arousal: 0.9 },

  // RED QUADRANT (High arousal, negative valence)
  Asqueado: { valence: -0.7, arousal: 0.3 },
  Intranquilo: { valence: -0.5, arousal: 0.5 },
  Alarmado: { valence: -0.6, arousal: 0.7 },
  Incómodo: { valence: -0.5, arousal: 0.4 },
  Fastidiado: { valence: -0.5, arousal: 0.3 },
  Ansioso: { valence: -0.6, arousal: 0.6 },
  Temeroso: { valence: -0.6, arousal: 0.6 },
  Preocupado: { valence: -0.5, arousal: 0.5 },
  Irritado: { valence: -0.6, arousal: 0.5 },
  Molesto: { valence: -0.5, arousal: 0.4 },
  "Hirviendo de rabia": { valence: -0.9, arousal: 0.9 },
  Asustado: { valence: -0.7, arousal: 0.7 },
  Enfadado: { valence: -0.7, arousal: 0.6 },
  Nervioso: { valence: -0.5, arousal: 0.7 },
  Inquieto: { valence: -0.5, arousal: 0.6 },
  Rabioso: { valence: -0.8, arousal: 0.8 },
  Furioso: { valence: -0.8, arousal: 0.9 },
  Frustrado: { valence: -0.7, arousal: 0.6 },
  Tenso: { valence: -0.6, arousal: 0.7 },
  Desconcertado: { valence: -0.4, arousal: 0.6 },
  Enfurecido: { valence: -0.9, arousal: 0.9 },
  Aterrorizado: { valence: -0.9, arousal: 0.9 },
  Estresado: { valence: -0.7, arousal: 0.8 },
  Alterado: { valence: -0.6, arousal: 0.8 },
  Impactado: { valence: -0.5, arousal: 0.8 },

  // BLUE QUADRANT (Low arousal, negative valence)
  Desesperado: { valence: -0.9, arousal: -0.4 },
  "Sin esperanza": { valence: -0.9, arousal: -0.6 },
  Desolado: { valence: -0.9, arousal: -0.5 },
  Fundido: { valence: -0.7, arousal: -0.8 },
  "Sin energía": { valence: -0.6, arousal: -0.9 },
  Abatido: { valence: -0.8, arousal: -0.6 },
  Deprimido: { valence: -0.8, arousal: -0.7 },
  Huraño: { valence: -0.6, arousal: -0.6 },
  Agotado: { valence: -0.6, arousal: -0.9 },
  Fatigado: { valence: -0.5, arousal: -0.8 },
  Aislado: { valence: -0.7, arousal: -0.6 },
  Miserable: { valence: -0.9, arousal: -0.6 },
  Solitario: { valence: -0.7, arousal: -0.5 },
  Descorazonado: { valence: -0.7, arousal: -0.5 },
  Cansado: { valence: -0.4, arousal: -0.8 },
  Pesimista: { valence: -0.6, arousal: -0.5 },
  Sombrío: { valence: -0.7, arousal: -0.5 },
  Desanimado: { valence: -0.6, arousal: -0.6 },
  Triste: { valence: -0.7, arousal: -0.6 },
  Aburrido: { valence: -0.3, arousal: -0.7 },
  Disgustado: { valence: -0.6, arousal: -0.4 },
  Apagado: { valence: -0.5, arousal: -0.7 },
  Decepcionado: { valence: -0.6, arousal: -0.5 },
  Decaído: { valence: -0.5, arousal: -0.6 },
  Apático: { valence: -0.4, arousal: -0.8 },
}

export function getEmotionAxes(emotion: string): EmotionAxes {
  return EMOTION_TO_AXES[emotion] || { valence: 0, arousal: 0 }
}
